var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   x            ",
   "                                                                   xxxxxxxxxxx  ",
   "                                                                             x  ",
   "                                                   xx     xxx                x  ",
   "                            v       o o   xx xx    xx      xx   xx           x  ",
   "                        xxxxxxxx          xx!xx     x           xx        y  x  ",
   "                x   xx  xxxxxxxxxxxxxxx    xxx                  xx o         x  ",
   "                xx  x        xxxxxxxxxxx                        xx  y        x  ",
   "  xx                                    xxo o                   xx           x  ",
   "  x                     o                x                      xx           x  ",
   "  x                xxx                   xxxxx                  xx         o x  ",
   "  x           xxxx x    xxxx           o x       y           o  xx           x  ",
   "  x  @        x  x            xx    v    x     v                xxxx         x  ",
   "  xxxxxxxxxxxxx  x                xxxxxxxxxxxxxxxxxxxx     xxxxxxx           x  ",
   "                 x                x                  x     x     x!!!!!!!xxx!x  ",
   "                 x!!!!!!!!!!!!!!!!x                  x!!!!!x     xxxxxxxxxxxxx  ",
   "                 x!!!!!!!!!!!!!!!!x                  x!!!!!x                    ",
   "                 xxxxxxxxxxxxxxxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
   
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                               ",
   "x                            xxx                                x                               ",
   "x   @                         lx oo                             x                               ",
   "x                              x xx            xxx        x     x                               ",
   "xxxxxxxxxxxxxx  x  xxxxxxx     x xxx         xxxxxx  xx  xx     x                               ",
   "x            x!!x!!x           x            xxxxxx!!!xx!!!x     x                               ",
   "x            xxxxxxx           x xx        xxxxxxxxxxxxxxxx     x                               ",
   "x                              x!xxxx             lllll         x                               ",
   "x                       xxxxxxxxxxxxxxx                         xxxxxxxxxxxxxxxxxxxxxxxx        ",
   "           xxxxxxxxxxxxxx   l            x                         l   l   lx          xxxxxxx  ",
   "                                            xxxx           xxx              x             l   x ",
   "                                            x  x           x x       o      x                 x ",
   "    xxx        o                           xx  x!!!!!!!!!!!x x      xxx     x                 x ",
   "                                            x  x!!!!!!!!!!!x x              x                 x ",
   "          xxxxxxx                        x  x  x!!!!!!!!!!!x x   o      o   x                 x ",
   "                                     xx  xx x  x!!!!!!!!!!!x x  xx      xx                    x ",
   "                      v              xx!!xxox  x!!!!!!!!!!!x x                                x ",
   "                   xxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       o          v             x ",
   "!!!!!!!!!!!!!!!!!!!x      x!!!x                              x      xxx     xxxxxxxxxx        x ",
   "xxxxxxxxxxxxxxxxxxxx      xxxxx                              x              x  l  x           x ",
   "                                                             x!!!!!!!!!!!!!!x     x           x ",
   "                                                             xxxxxxxxxxxxxxxx     x           x ",
   "                                                             x                    x           x ",
   "                                                             x                   oxo          x ",
   "                                                             x            xxxx  xxxxxx        x ",
   "                                                             x                            xxxxx ",
   "                                                             x     xxxxx                      x ",
   "                                                             xo   xxxxxx    xxx               x ",
   "                                                             xxxx             xx  xxxxxx      x ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x "],
   
  ["                                                                              x                               ",
   "llllll      lllllllllll       llllllllll      lll   lllll                  xxxx                    llllllllll ",
   "                                                                         xxxxxx                               ",
   "                                                                              x                               ",
   "                                                                              x                               ",
   "                                                                           xxxxxxx                            ",
   "                                                                         xx       xx                          ",
   "                                                                                    x                         ",
   "                                                                                     x                        ",
   "                                                                   xxxx       v       x                       ",
   "                                                        v         x  xxxxxxxxxxxxxxx   x                      ",
   "                                                 xxxxxxxxxxxx       x     l             x                     ",
   "                                     v        xxx l      l          x                   x                     ",
   "                                xxxxxxxxxxx                        x       xxxxxxxxxxxxxxx                    ",
   "                                                                   x        l            x                    ",
   "                          xxxxx                                    x                     x                    ",
   "          xxxxxxxxxxxx                                            x                       x                   ",
   "        xx           x                                            x   v                   x                   ",
   "                  oo x  xx                                        xxxxxxxxx  xx  xxxxx    x                   ",
   "                     x  xxx    v                                  x  l    x      x l xoooox                   ",
   "       xxxx  xx  xxxxxxxxxxxxxxxxxx                               x       x      x   xxxxxx                   ",
   "                 l            l    x                            xx        x      x         xx                 ",
   "                                                               x                             x                ",
   "                                  xxxxxxxx                   xxx                             xxx              ",
   "                                          x                    x o                        o  x                ",
   "                                                                xxxx   xxxx  v   xxxxx   xxxx                 ",
   "                                             xxxxxx               x       xxxxxxxx  l     x                   ",
   "                                                   x              x                       x                   ",
   "                                                                  x                       x                   ",
   "                                                     xxxx         x                       x                   ",
   "                                                                   x                     x    o               ",
   "                                                            xxxxxxxx xxxxxxxxxx xxxxxxx  xxxxxxxx             ",
   "                                                              xxlllx xllllllllx xll llx  xlllxx               ",
   "                                                               xxllx x        x x     x!!xllxx    x           ",
   "                                                     xxxxx      xxlx x        x x      xxxlx   xxxxx          ",
   "                                                   xxx           xxx                     xx                   ",
   "       @                                                          xx                                 xxxx     ",
   "                          p                 xxx                   xx        v     o                           ",
   "  xxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  x  xxxxxxxxxxx",
   "                     x!!!!!!!!!!x                                                            x!!!!!x          "],
   
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           ",
   "x            =                           xx                              x  l   l   l   l         xxxxxxxxx   ",
   "x  o p       =                           xx    v                                                          x   ",
   "x            =                           xx                                                               x   ",
   "xxxxxxxxxxxxxxx     x                    xx               xxxxxxxxxxxxxxxx                                x   ",
   "x                  xxx                o  xx          x                   x                                x   ",
   "x                 xxxxx!!!!!!!!!!!!!!!!!!xx           v                  xxx                           o  x   ",
   "x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                       x                         xxxxxxxx   ",
   "xxxx                                     xx       xxxx             v     x   xx           xxxxxxxxxx          ",
   "x                                        xxx         xxxxxxx             x                x                   ",
   "x    xxxxxx                                           x                  x        xxxxx   x                   ",
   "x         xxxxxxxx                                    x      v           x           l    x                   ",
   "x!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxx        x                  x xxxx           x                   ",
   "xxxxxxxxxxxxxxxxxxxxx                        x        x   xxxxxxxxx   xxxx                x                   ",
   "x                                            xx       =   =              x                x                   ",
   "x                                  x=        xx       =   =              x       xxx      x                   ",
   "x                               xxxx    o   =xxx      =   =              x                x                   ",
   "x                      xxxxxxxxxxxxxxxxxxxxxxxxxxxx   =   =              x            xxx x                   ",
   "x     @                      lxxxxxxxxxl   l x        =xx =              x                x                   ",
   "x                               l   l        x        =   =  xx   p      x                x                   ",
   "xxxxxxxxxxxxxxxxxxxxxx                       x        =   =  xxx         x     xxxxx      x                   ",
   "                     x                       x        =   =  xxxxx       x                x                   ",
   "                     x       p               x!!!!!!!!!!!!!!!xxxxxxxxxxxxx                xxxxxxxxxxxxx       ",
   "                     xxxxx                   x!!!!!!!!!!!!!!!x            xxx                         x       ",
   "                         x                   x!!!!!!!!!!!!!!!x                                        x       ",
   "                         x                   x!!!!!!!!!!!!!!!x            v                           x       ",
   "                         x                   xxxxxxxxxxxxxxxxx          xxxxxxxxxxx   xxxxxxxxx       x       ",
   "                         x                                                                        x  ox       ",
   "                         x                                                                           xx       ",
   "                         x                   xxxxxxxxxxxxxxxxx             x                         xx       ",
   "                         x                   x               x             x                     xxxxxx       ",
   "                         x o                xx               x        v  xxx      =   =          xxxxxx       ",
   "                         xxx               xxx               xxxxxxxxxxxxxxx   =  =   =          xxxxxx       ",
   "                         x!!!!!!!!!!!!!!!!!!!x                             xxxxxxxxxxxxxxxxxxxxxxx            "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
